name: bumper
on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  update-dep:
    strategy:
      matrix:
        deno: ["1.5.1"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Deno
        uses: denolib/setup-deno@v2
        with:
          deno-version: ${{ matrix.deno }}

      - name: Update Dependencies
        run: deno run --allow-net --allow-read --allow-write https://deno.land/x/dmm/mod.ts update

      - name: Update Test Dependencies
        run: |
          cd tests
          deno run --allow-net --allow-read --allow-write https://deno.land/x/dmm/mod.ts update

      - name: Update Create App Dependencies
        run: |
          cd console/create_app
          deno run --allow-net --allow-read --allow-write https://deno.land/x/dmm/mod.ts update

      - name: Bump Versions
        run: deno run --allow-net --allow-write --allow-read console/bumper_ci_service.ts

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v2
        with:
          token: ${{ secrets.CI_USER_PAT }}
          labels: |
            chore
          commit-message: "chore: Update dependencies"
          title: "chore: Update dependencies"
          body: This was auto-generated by GitHub Actions.
          branch: update-dependencies
