name: bumper
on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  update-dep:
    strategy:
      matrix:
        deno: ["1.5.1"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Deno
        uses: denolib/setup-deno@v2
        with:
          deno-version: ${{ matrix.deno }}

      - name: Update Main Dependencies
        run: deno run --allow-net --allow-read --allow-write https://deno.land/x/dmm/mod.ts update

      - name: Update CSRF Dependencies
        run: |
          cd csrf
          deno run --allow-net --allow-read --allow-write https://deno.land/x/dmm/mod.ts update

      - name: Bump Versons
        run: deno run --allow-read --allow-net --allow-write console/bumper_ci_service.ts

      - name: Update Cors Dependencies
        run: |
          cd cors
          deno run -A https://deno.land/x/dmm/mod.ts update

      #- name: Update Test Dependencies
      #  run: |
      #    cd tests
      #    deno run --allow-net --allow-read --allow-write https://deno.land/x/dmm/mod.ts update

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v2
        with:
          token: ${{ secrets.CI_USER_PAT }}
          commit-message: Update dependencies
          title: Update dependencies
          body: This was auto-generated by GitHub Actions.
          branch: update-dependencies
