name: master

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  tests:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        deno: ["1.4.6"]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - name: Install Deno v${{ matrix.deno }}
        uses: denolib/setup-deno@v2
        with:
          deno-version: ${{ matrix.deno }}

      - name: Dexter
        run: deno test --allow-env --allow-net dexter/tests/

      - name: Paladin
        run: deno test --allow-env --allow-net paladin/tests/

      - name: CSRF
        run: |
          cd csrf/tests
          deno test --allow-net --allow-env --config tsconfig.json

  linter:
    strategy:
      matrix:
        deno: ["1.4.6"]
    # Only one OS is required since fmt is cross platform
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Deno v${{ matrix.deno }}
        uses: denolib/setup-deno@v2
        with:
          deno-version: ${{ matrix.deno }}

      - name: Formatter
        run: deno fmt --check
