name: master

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  tests:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        deno: ["1.2.1"]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - name: Install Deno v${{ matrix.deno }}
        uses: denolib/setup-deno@v2
        with:
          deno-version: ${{ matrix.deno }}

      - name: Unit
        run: deno test tests/unit/tests.ts --config tsconfig.json --allow-net --allow-write --allow-read --allow-env

      - name: Integration
        run: |
          deno test --allow-all --config tsconfig.json tests/integration/app_3000_resources/tests.ts
          deno test --allow-all --config tsconfig.json tests/integration/app_3001_views/tests.ts
          # deno test --allow-all --config tsconfig.json tests/integration/app_3002_https/tests.ts
          deno test --allow-all --config tsconfig.json tests/integration/app_3003_middleware/tests.ts
          deno test --allow-all --config tsconfig.json tests/integration/app_3004_pretty_links/tests.ts
          deno test --allow-all --config tsconfig.json tests/integration/app_3005_middleware_resource_level/tests.ts

      - name: Create APP
        run: |
          deno cache create_app.ts
          deno test tests/cli/create_app_test.ts --allow-read --allow-write --allow-run --allow-env

  linter:
    # Only one OS is required since fmt is cross platform
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Deno v${{ matrix.deno }}
        uses: denolib/setup-deno@master

      - name: Formatter
        run: deno fmt --check
