name: Master

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  tests:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - name: Install Deno (master branch)
        uses: denolib/setup-deno@master

      - name: Unit Tests: Create App (local)
        run: |
          deno cache create_app.ts
          deno test tests/console/create_app/create_app_test_local.ts --allow-read --allow-write --allow-run --allow-env

      - name: Unit Tests: Create App (http)
        run: |
          deno test tests/unit/console/create_app/create_app_test_http.ts --allow-read --allow-write --allow-run --allow-env --allow-net

      - name: Unit Tests: Console
        run: deno test --allow-net --allow-write --allow-read --allow-env --config tsconfig.json tests/unit/console

      - name: Unit Tests: Core
        run: deno test --allow-net --allow-write --allow-read --allow-env --config tsconfig.json tests/unit/src/core

      - name: Integration Tests
        run: |
          deno test --allow-all --config tsconfig.json tests/integration/app_3000_resources/
          # deno test --allow-all --config tsconfig.json tests/integration/app_3002_https/
          deno test --allow-all --config tsconfig.json tests/integration/app_3003_middleware/

      - name: Check: `deno run` works on app created by create-app.ts --api
        run: |
          mkdir tmp1
          cd tmp1
          echo "export { Drash } from '../mod.ts'" > ../console/create_app/deps.ts # so the create app can target the local version instead of a versioned one
          deno run -A ../create_app.ts --api
          echo "server.close()" >> app.ts
          deno run -A app.ts

      - name: Check: `deno run` works on app created by create_app.ts --web-app
        run: |
          mkdir tmp2
          cd tmp2
          echo "export { Drash } from '../mod.ts'" > ../console/create_app/deps.ts # so the create app can target the local version instead of a versioned one
          deno run -A ../create_app.ts --web-app
          echo "server.close()" >> app.ts
          deno run -A app.ts

      - name: Check: `npm run buildVue` is available in create_app.ts --web-app --with-vue
        run: |
          mkdir tmp3
          cd tmp3
          deno run -A ../create_app.ts --web-app --with-vue
          npm i
          npm run buildVue

      - name: Check: `npm run buildReact` is available in create_app.ts --web-app --with-react
        run: |
          mkdir tmp4
          cd tmp4
          deno run -A ../create_app.ts --web-app --with-react
          npm i
          npm run buildReact

  benchmarks:
    strategy:
      matrix:
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - name: Install Deno (master branch)
        uses: denolib/setup-deno@master

      - name: Setup Node 13
        uses: actions/setup-node@v1
        with:
          node-version: '13'

      - name: Install Autocannon
        run: npm install -g autocannon

      - name: Run Drash application
        run: deno run --allow-net ./console/benchmark_app.ts &

      - name: Run Autocannon against Drash application
        run: autocannon -c 40 -d 10 -j http://localhost:1447

  code_quality:
    # Only one OS is required since fmt is cross platform
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Deno (master branch)
        uses: denolib/setup-deno@master

      - name: Check: `deno lint` passes
        run: deno lint

      - name: Check: `deno fmt` passes
        run: deno fmt --check
