name: pre-release

on:
  create

jobs:

  # Make a PR to master from a new branch with changes, and delete the created one
  update-versions:

    # Only run when a release-v* branch is created, and not by drashbot
    if: contains(github.ref, 'release-v') && !contains(github.event.sender.login, 'drashbot')

    strategy:
      matrix:
        deno: ["1.5.1"]

    runs-on: ubuntu-latest

    steps:

      - name: Checkout master
        uses: actions/checkout@v2
        with:
          ref: master

      - name: Delete Remote Release Branch
        run: git push --delete origin ${{ github.ref }}

      - name: Install Deno
        uses: denolib/setup-deno@v2
        with:
          deno-version: ${{ matrix.deno }}

      - name: Bump Versions
        run: deno run -A ./console/bumper_ci_service.ts --version=${{ github.ref }} # version passed so we know what the new release version will be

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v2
        with:
          token: ${{ secrets.CI_USER_PAT }}
          commit-message: bump versions
          title: bump versions
          body: This was auto-generated by GitHub Actions.
          branch: release # Can change it to ${{ github.ref }} to be the branch name, but then we need to figure out how to stop this worjflow running  when it creates another "release-vx.x.x" branch
